{
 "title": "Atlassian Instance Health Exporter",
 "tags": [
  "prometheus",
  "atlassian_instance_health_exporter"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Prometheus to Exporter Responding",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "UP" }
   ],
   "targets": [
    {
     "expr": "up{job=\"atlassian_instance_health_exporter\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Exporter to Rest Responding",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "UP" }
   ],
   "targets": [
    {
     "expr": "atlassian_instance_health_scrape_url_up == 1",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "Is Healthy",
   "type": "graph",
   "gridPos": { "h": 14, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (tag, name) (atlassian_instance_health == 1)",
     "legendFormat": "{{tag}} - {{name}}"
    }
   ]
  },
  {
   "title": "Not Healthy",
   "type": "graph",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (tag, name) (atlassian_instance_health!= 1)",
     "legendFormat": "{{tag}} - {{name}}"
    }
   ]
  },
  {
   "title": "Service Collect Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "atlassian_instance_health_collect_duration_seconds",
     "legendFormat": "{{fqdn}}"
    }
   ]
  }
 ]
}